version: "3.9"

services:
  front:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"  # ⚠ Port modifié pour éviter le conflit
    env_file:
      - ./db/.env
    environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/parcauto.sql:/docker-entrypoint-initdb.d/parcauto.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8089:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=monuser
      - PMA_PASSWORD=root
    depends_on:
      - db

volumes:
  db_data:
